packages:
  - 'apps/*'
  - 'contracts/*'
  - 'sdk/*'
  - '!sdk\airdrop-sdk\airdrop'
  - '!sdk\airdrop-sdk\node'
  - '!sdk\airdrop-sdk\invite'
  - '!sdk\airdrop-sdk\types'
  - '!sdk\airdrop-sdk\utils'
